name: AbyssVouchers
version: '1.0.0'
main: net.abyssdev.abyssvouchers.AbyssVouchers
api-version: 1.13
depend:
    - AbyssLib
authors:
    - Relocation
description: Advanced vouchers plugin made by AbyssDev
website: https://abyssdev.net
